# appspec.yml for AWS CodeDeploy
# Comments explain each key/pair below.

version: 0.0            # appspec file version (CodeDeploy uses this to parse)
os: linux               # target OS for the deployment (linux here)

files:                  # files to copy from the revision bundle to the instance
  - source: /index.html         # path inside the revision bundle (root-relative)
    destination: /var/www/html/ # absolute path on the instance where the file will be copied


hooks:                  # lifecycle hooks — run scripts at specific deployment phases
  BeforeInstall:        # runs before the application files are copied (used for prep)
    - location: scripts/install_dependencies  # script path inside the bundle to run
      timeout: 300                         # seconds to wait before aborting the script
      runas: root                          # user to run the script as on the instance
    - location: scripts/start_server      # additional prep script (note: common pattern is to stop app in ApplicationStop, install deps, then start in AfterInstall/ApplicationStart)
      timeout: 300
      runas: root
  ApplicationStop:      # runs when stopping the existing application version (before install on some workflows)
    - location: scripts/stop_server       # script to stop the running service/process
      timeout: 300
      runas: root