jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        run: |
          git init .
          git config --global init.defaultBranch main
          git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git fetch --depth=1 origin ${{ github.sha }}
          git checkout --force FETCH_HEAD

      - name: Configure AWS CLI (install if missing, otherwise use existing)
        run: |
          set -euxo pipefail
          echo "::add-mask::${{ secrets.AWS_ACCESS_KEY_ID }}"
          echo "::add-mask::${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          export AWS_ACCESS_KEY_ID='${{ secrets.AWS_ACCESS_KEY_ID }}'
          export AWS_SECRET_ACCESS_KEY='${{ secrets.AWS_SECRET_ACCESS_KEY }}'
          export AWS_REGION='${{ secrets.AWS_REGION }}'
          export PATH="/usr/local/bin:$PATH"

          sudo apt-get update -y
          sudo apt-get install -y unzip curl jq zip

          if command -v aws >/dev/null 2>&1; then
            echo "AWS CLI already installed:"
            aws --version
          else
            echo "Installing AWS CLI v2…"
            curl -sSL "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip -q awscliv2.zip
            sudo ./aws/install
            aws --version
          fi

          aws sts get-caller-identity
